//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.26 at 05:59:36 PM CEST 
//


package xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="designMethodologyApproach" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="findings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="researchLimitationsImplications" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="practicalImplications" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originalityValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "purpose",
    "designMethodologyApproach",
    "findings",
    "researchLimitationsImplications",
    "practicalImplications",
    "originalityValue"
})
@XmlRootElement(name = "defaultAbstract")
public class DefaultAbstract {

    @XmlElement(required = true)
    protected String purpose;
    @XmlElement(required = true)
    protected String designMethodologyApproach;
    @XmlElement(required = true)
    protected String findings;
    @XmlElement(required = true)
    protected String researchLimitationsImplications;
    @XmlElement(required = true)
    protected String practicalImplications;
    @XmlElement(required = true)
    protected String originalityValue;

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the designMethodologyApproach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignMethodologyApproach() {
        return designMethodologyApproach;
    }

    /**
     * Sets the value of the designMethodologyApproach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignMethodologyApproach(String value) {
        this.designMethodologyApproach = value;
    }

    /**
     * Gets the value of the findings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFindings() {
        return findings;
    }

    /**
     * Sets the value of the findings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFindings(String value) {
        this.findings = value;
    }

    /**
     * Gets the value of the researchLimitationsImplications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResearchLimitationsImplications() {
        return researchLimitationsImplications;
    }

    /**
     * Sets the value of the researchLimitationsImplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResearchLimitationsImplications(String value) {
        this.researchLimitationsImplications = value;
    }

    /**
     * Gets the value of the practicalImplications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPracticalImplications() {
        return practicalImplications;
    }

    /**
     * Sets the value of the practicalImplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPracticalImplications(String value) {
        this.practicalImplications = value;
    }

    /**
     * Gets the value of the originalityValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalityValue() {
        return originalityValue;
    }

    /**
     * Sets the value of the originalityValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalityValue(String value) {
        this.originalityValue = value;
    }

}
